//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyse
    {
        public int id { get; set; }
        public string entity_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date_analyse { get; set; }
        public string Description { get; set; }
        public string version { get; set; }
    
        public virtual entities entities { get; set; }
        public virtual UserSpot UserSpot { get; set; }
    }
}
