//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_CONTRACT
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Internal_Contract_Number { get; set; }
        public string Currency_Code { get; set; }
        public string Customer_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Product_Code { get; set; }
        public Nullable<float> Principal_amount_in_currency { get; set; }
        public Nullable<float> Principal_amount_in_local_currency { get; set; }
        public Nullable<float> Outstanding_amount_in_currency { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency { get; set; }
        public string GL_internal_Number { get; set; }
        public string GL_reporting_Number { get; set; }
        public string Type_Amount { get; set; }
        public Nullable<float> Book_amount { get; set; }
        public string Debit_Credit { get; set; }
        public string Doubtful { get; set; }
        public Nullable<float> Provision_Rate { get; set; }
        public string Attribute_1 { get; set; }
        public string Attribute_2 { get; set; }
        public string Attribute_3 { get; set; }
        public string Attribute_4 { get; set; }
        public string Attribute_5 { get; set; }
    }
}
