//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_ARC
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Internal_Guarantee_Number { get; set; }
        public string Internal_Contract_Number { get; set; }
        public string Guarantee_Class { get; set; }
        public Nullable<float> Guarantee_Weighting_amount { get; set; }
        public string Guarantee_Customer { get; set; }
        public string Guarantee_currency { get; set; }
        public string GL_internal_Number { get; set; }
        public Nullable<float> Guarantee_assigned_amount { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency { get; set; }
    }
}
