//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_ASSET
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Portfolio { get; set; }
        public string Portfolio_Description { get; set; }
        public string Category { get; set; }
        public string Category_Description { get; set; }
        public string Sub_Category { get; set; }
        public string Sub_Category_Description { get; set; }
        public string Sub_Portfolio { get; set; }
        public string Sub_Portfolio_Description { get; set; }
        public string Exposition_Type { get; set; }
        public string Account { get; set; }
        public string Balance_Off_Sheet { get; set; }
        public string Currency_Code { get; set; }
        public string Customer_Code { get; set; }
        public string Internal_Contract_Number { get; set; }
        public Nullable<float> Outstanding_amount_in_currency { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency { get; set; }
        public Nullable<float> Provision_affected_amount { get; set; }
        public string WeightingCode { get; set; }
        public Nullable<float> Weighting { get; set; }
        public Nullable<float> Credit_Conversion_Factor { get; set; }
        public Nullable<float> CreditProtection { get; set; }
        public Nullable<float> FinancialCollateral { get; set; }
        public Nullable<float> RiskWeightedExposureAmounts { get; set; }
    }
}
