//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_COREP_CA
    {
        public System.DateTime ID_DATE { get; set; }
        public string ID_ENTITY { get; set; }
        public string ID_AMOUNT { get; set; }
        public Nullable<long> AMOUNT { get; set; }
    }
}
