//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_CUSOMER_CMDR
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Customer_Code { get; set; }
        public string Company_group { get; set; }
        public string Company_group_name { get; set; }
        public Nullable<float> Company_group_total_Outstanding { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_ID_Number { get; set; }
        public string Activity_Regulator_Code { get; set; }
        public string Internal_Notation { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency { get; set; }
        public Nullable<float> Doubtful_amount_in_local_currency { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency_1 { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency_2a { get; set; }
        public Nullable<float> Outstanding_amount_in_local_currency_2b { get; set; }
        public Nullable<float> Provision_affected_amount { get; set; }
        public Nullable<float> Outstanding_amount_Weighting { get; set; }
        public Nullable<float> Guarantee_assigned_amount { get; set; }
    }
}
