//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_COREP_CR
    {
        public string ID_PONDERATION { get; set; }
        public string ID_CAT_EXPOSITION { get; set; }
        public string ID_EXPOSITON { get; set; }
        public System.DateTime ID_Date { get; set; }
        public string ID_AMOUNT { get; set; }
        public Nullable<int> AMOUNT { get; set; }
    }
}
