//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_ACCOUNT
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Basel_In { get; set; }
        public string Basel_Segment { get; set; }
        public Nullable<float> Credit_Conversion_Factor { get; set; }
        public string Balance_Off_Sheet { get; set; }
        public string Sens_Code { get; set; }
        public Nullable<bool> Is_Commitment { get; set; }
        public Nullable<bool> Is_Provision { get; set; }
        public Nullable<bool> Is_Doubtful { get; set; }
        public Nullable<bool> Is_Accrued_Interest { get; set; }
    }
}
