//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_CURRENCY
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Version { get; set; }
        public string Currency { get; set; }
        public Nullable<float> Exchange_Rate { get; set; }
    }
}
