//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_GUARANTEE_TYPE
    {
        public string Bank_Code { get; set; }
        public string Process_Date { get; set; }
        public string Guarantee_Account { get; set; }
        public string Guarantee_Type_Description { get; set; }
        public string Guarantee_Class { get; set; }
        public Nullable<float> Guarantee_Weighting { get; set; }
    }
}
