//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpootLight
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpotLightDATAEntities : DbContext
    {
        public SpotLightDATAEntities()
            : base("name=SpotLightDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_AMOUNT_TYPE> DM_AMOUNT_TYPE { get; set; }
        public virtual DbSet<DM_CAT_EXPOSITION> DM_CAT_EXPOSITION { get; set; }
        public virtual DbSet<DM_ENTITY> DM_ENTITY { get; set; }
        public virtual DbSet<DM_PONDERATION> DM_PONDERATION { get; set; }
        public virtual DbSet<DM_TYPE_EXPOSITION> DM_TYPE_EXPOSITION { get; set; }
        public virtual DbSet<DT_CONTRACT> DT_CONTRACT { get; set; }
        public virtual DbSet<DT_CUSTOMER> DT_CUSTOMER { get; set; }
        public virtual DbSet<DT_GUARANTEE> DT_GUARANTEE { get; set; }
        public virtual DbSet<FT_COREP_CA> FT_COREP_CA { get; set; }
        public virtual DbSet<FT_COREP_CR> FT_COREP_CR { get; set; }
        public virtual DbSet<PR_ACCOUNT> PR_ACCOUNT { get; set; }
        public virtual DbSet<PR_BASEL_CATEGORY> PR_BASEL_CATEGORY { get; set; }
        public virtual DbSet<PR_BASEL_PORTFOLIO> PR_BASEL_PORTFOLIO { get; set; }
        public virtual DbSet<PR_CURRENCY> PR_CURRENCY { get; set; }
        public virtual DbSet<PR_ECONOMIC_SECTOR> PR_ECONOMIC_SECTOR { get; set; }
        public virtual DbSet<PR_GUARANTEE_TYPE> PR_GUARANTEE_TYPE { get; set; }
    }
}
